version: '3.9'

services:

   pgadmin4:
     # https://hub.docker.com/r/dpage/pgadmin4/
     image: dpage/pgadmin4
     environment:
       PGADMIN_DEFAULT_EMAIL: admin@example.com
       PGADMIN_DEFAULT_PASSWORD: password
       PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
     ports:
       - 8080:80
     volumes:
       - ./servers.json:/pgadmin4/servers.json
